#!/bin/sh
#
# $Id: dhcp3-server.init.d,v 1.4 2003/07/13 19:12:41 mdz Exp $
#
# NOTE:
#   - setup of network is controlled by 'reneo.ROS'
#

case "$1" in
	start)
		;;
	stop)
		;;
	restart | force-reload)
		$0 stop
		$0 start
		if [ "$?" != "0" ]; then
			exit 1
		fi
		;;
	*)
		echo "Usage: $0 {start|stop|restart|force-reload}"
		exit 1
esac

exit 0
