#!/bin/sh
#
# $Id: dhcp3-relay,v 1.1 2004/04/16 15:41:08 ml Exp $
#
# NOTE:
#   - setup of network is controlled by 'reneo.ROS'
#

case "$1" in
	start)
		;;
	stop)
		;;
	restart | force-reload)
		$0 stop
		$0 start
		;;
	*)
		echo "Usage: $0 {start|stop|restart|force-reload}"
		exit 1
esac

exit 0
