#! /bin/sh
#
# urandom	This script saves the random seed between reboots.
#		It is called from the boot, halt and reboot scripts.
#
# Version:	@(#)urandom  1.33  22-Jun-1998  miquels@cistron.nl
#
# NOTE:
#   - since this is a live image, nothing much to do ...
#

[ -c /dev/urandom ] || exit 0
#. /etc/default/rcS

case "$1" in
	start|"")
		# check for read only file system
		;;
	stop)
		;;
	*)
		echo "Usage: urandom {start|stop}" >&2
		exit 1
		;;
esac
