#!/bin/sh
#
# Start the network....
#

# Debian ifupdown needs the /run/network lock directory
#
# NOTE:
#   - setup of network is controlled by 'reneo.ROS'
#   - focus on creating needed folder structure, and
#     skip everything else ...
#

mkdir -p /run/network

case "$1" in
  start)
	;;
  stop)
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

